Repository openenclave/oeedger8r-cpp, pull requests merged in 2020-10, with the labels that each got.

#51 Disable deepcopy for out parameters
  parser.cpp
  test/attributes/CMakeLists.txt
  test/attributes/attributes.edl
  test/comprehensive/edl/deepcopy.edl
  test/comprehensive/enc/testdeepcopy.cpp
  test/comprehensive/host/testdeepcopy.cpp
  utils.h
Labels: approved, dco-signoff: yes, size/M

#47 add build badge
  README.md
Labels: approved, area/devtools, dco-signoff: yes, lgtm, sig/test-infra, size/XS

#52 Prevent struct members used by size/count attributes from being modified by the callee during deep copy
  ast.h
  parser.cpp
  parser.h
  test/attributes/CMakeLists.txt
  test/attributes/attributes.edl
  test/comprehensive/edl/deepcopy.edl
  test/comprehensive/enc/testdeepcopy.cpp
  test/comprehensive/host/testdeepcopy.cpp
  utils.h
  w_emitter.h
Labels: approved, dco-signoff: yes, lgtm, size/XL

#50 Fix TOCTOU pattern for string copy in ocalls
  w_emitter.h
Labels: approved, dco-signoff: yes, lgtm, size/S

#54 Add tests for isary, isptr attributes on pointer types
  test/attributes/CMakeLists.txt
  test/attributes/attributes.edl
Labels: approved, dco-signoff: yes, lgtm, size/S
