Repository openenclave/oeedger8r-cpp, pull requests merged in 2021-04, with the labels that each got.

#76 Remove corelibc
  test/comprehensive/enc/testpointer.cpp
  test/comprehensive/enc/teststring.cpp
  test/comprehensive/host/teststring.cpp
  test/virtual/enclave.cpp
  test/virtual/include/openenclave/corelibc/bits/defs.h
  test/virtual/include/openenclave/corelibc/errno.h
  test/virtual/include/openenclave/corelibc/limits.h
  test/virtual/include/openenclave/corelibc/stdlib.h
  test/virtual/include/openenclave/corelibc/string.h
  test/virtual/include/openenclave/corelibc/wchar.h
  test/virtual/include/openenclave/edger8r/enclave.h
Labels: approved, dco-signoff: yes, lgtm, size/XL

#75 Remove the deepcopy out experimental flag
  src/parser.cpp
  test/attributes/CMakeLists.txt
  test/attributes/attributes.edl
  test/comprehensive/enc/CMakeLists.txt
  test/comprehensive/host/CMakeLists.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#69 replace brmclaren with manojrupireddy as owner for oeedgr8r
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#77 Set count to one by default and prevent the use of size for user-defined
  src/f_emitter.h
  src/parser.cpp
  src/utils.h
  src/w_emitter.h
  test/attributes/CMakeLists.txt
  test/attributes/attributes.edl
  test/comprehensive/edl/deepcopy.edl
  test/comprehensive/enc/testdeepcopy.cpp
  test/comprehensive/host/testdeepcopy.cpp
Labels: approved, dco-signoff: yes, lgtm, size/L

#78 change auto generated variable names
  src/c_emitter.h
  src/f_emitter.h
  src/w_emitter.h
  test/comprehensive/edltestutils.h
  test/comprehensive/host/teststring.cpp
Labels: approved, dco-signoff: yes, lgtm, size/S
