Repository openenclave/oeedger8r-cpp, pull requests merged in 2021-01, with the labels that each got.

#60 Update oeedger8r
  CMakeLists.txt
  test/virtual/enclave_impl.h
Labels: approved, dco-signoff: yes, lgtm, size/S

#61 Format using correct clang-format version
  f_emitter.h
Labels: approved, dco-signoff: yes, lgtm, size/XS

#55 Support deepcopy of variable length out parameters
  c_emitter.h
  f_emitter.h
  main.cpp
  parser.cpp
  parser.h
  test/attributes/CMakeLists.txt
  test/comprehensive/edl/deepcopy.edl
  test/comprehensive/enc/testdeepcopy.cpp
  test/comprehensive/host/testdeepcopy.cpp
  test/virtual/enclave.cpp
  test/virtual/enclave_impl.h
  test/virtual/host.cpp
  test/virtual/include/openenclave/corelibc/stdlib.h
  test/virtual/include/openenclave/edger8r/common.h
  test/virtual/include/openenclave/edger8r/enclave.h
  test/virtual/include/openenclave/edger8r/host.h
  utils.h
  w_emitter.h
Labels: approved, dco-signoff: yes, lgtm, prowExample, size/XXL

#62 Upgrade to clang-format-8
  scripts/format-code
Labels: approved, dco-signoff: yes, lgtm, size/XS

#63 Move source files under src/
  CMakeLists.txt
  src/CMakeLists.txt
  src/args_h_emitter.h
  src/ast.h
  src/c_emitter.h
  src/f_emitter.h
  src/h_emitter.h
  src/lexer.cpp
  src/lexer.h
  src/main.cpp
  src/parser.cpp
  src/parser.h
  src/preprocessor.h
  src/utils.h
  src/w_emitter.h
Labels: approved, dco-signoff: yes, lgtm, size/M

#64 Correctly select compiler.
  CMakeLists.txt
Labels: approved, dco-signoff: yes, lgtm, size/S
