Repository openenclave/oeedger8r-cpp, pull requests merged in 2021-02, with the labels that each got.

#31 Enforce safe multiplication
  src/f_emitter.h
  src/utils.h
  src/w_emitter.h
  test/CMakeLists.txt
  test/comprehensive/host/teststring.cpp
  test/safe_math/CMakeLists.txt
  test/safe_math/enc/CMakeLists.txt
  test/safe_math/enc/enc.cpp
  test/safe_math/host/CMakeLists.txt
  test/safe_math/host/host.cpp
  test/safe_math/safe_math.edl
  test/virtual/include/openenclave/edger8r/common.h
Labels: approved, dco-signoff: yes, lgtm, size/XL

#65 Emit warnings for pointer array parameters
  src/parser.cpp
  test/attributes/CMakeLists.txt
  test/attributes/attributes.edl
Labels: approved, dco-signoff: yes, lgtm, size/M

#67 Add warning options for non-serializable cases
  src/main.cpp
  src/parser.cpp
  src/parser.h
  src/utils.h
  src/warnings.h
  test/CMakeLists.txt
  test/warnings/CMakeLists.txt
  test/warnings/warnings.edl
  test/warnings/werror.edl
Labels: approved, dco-signoff: yes, lgtm, size/XL

#66 Update the generated variable names to conform OE guidelines
  src/c_emitter.h
  src/f_emitter.h
  src/w_emitter.h
  test/comprehensive/edltestutils.h
  test/comprehensive/enc/testerrno.cpp
  test/comprehensive/host/teststring.cpp
  test/virtual/enclave.cpp
  test/virtual/include/openenclave/edger8r/common.h
Labels: approved, dco-signoff: yes, lgtm, size/L

#59 Update read me build badge to reference current infrastracture
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS, ¯\_(ツ)_/¯

#70 Add OE_ADD_ARG_SIZE macro
  src/f_emitter.h
  src/w_emitter.h
  test/comprehensive/host/teststring.cpp
  test/virtual/include/openenclave/edger8r/common.h
Labels: approved, dco-signoff: yes, lgtm, size/L

#71 Fix the check of foreign ptr warning
  src/parser.cpp
  test/warnings/CMakeLists.txt
  test/warnings/warnings.edl
Labels: approved, dco-signoff: yes, lgtm, size/M

#72 Refactor warning mechanisms
  src/main.cpp
  src/parser.cpp
  src/parser.h
  src/warnings.h
  test/attributes/CMakeLists.txt
  test/behavior/CMakeLists.txt
  test/behavior/allow_list.edl
  test/behavior/count_signedness.edl
  test/behavior/size_signedness.edl
  test/import/CMakeLists.txt
  test/warnings/CMakeLists.txt
  test/warnings/warnings.edl
  test/warnings/werror.edl
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XL
